"""Run the fault-injection corpus and write reports/fault_injection.md and .json.

    python scripts/fault_report.py           # regenerate the report
    python scripts/fault_report.py --check   # exit 1 if either committed file is stale

The output is deterministic (no timestamps or timings), so CI can check it.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from aegisops.verification.models import CheckSeverity, Verdict  # noqa: E402
from tests.fault_injection.corpus import SEEDS, clean_case  # noqa: E402
from tests.fault_injection.mutators import MUTATORS  # noqa: E402

OUTPUT = ROOT / "reports" / "fault_injection.md"
OUTPUT_JSON = OUTPUT.with_suffix(".json")


def build_report() -> str:
    return build()[0]


def build() -> tuple[str, str]:
    """The Markdown report and the same numbers as JSON (for the console's Evals page)."""
    clean_reports = [clean_case(seed).verify() for seed in SEEDS]
    false_blocks = sum(bool(report.blocking_check_ids) for report in clean_reports)
    clean_flags = sum(bool(report.failed()) for report in clean_reports)
    gate_blocks = sum(report.safety_gate_blocked for report in clean_reports)

    rows: list[str] = []
    classes: list[dict[str, object]] = []
    classes_caught = 0
    total_caught = 0
    for mutator in MUTATORS:
        caught = blocked = 0
        collateral: Counter[str] = Counter()
        for seed in SEEDS:
            report = mutator.apply(clean_case(seed)).verify()
            failed = {check.id for check in report.failed()}
            caught += mutator.expected_check in failed
            blocked += report.verdict == Verdict.BLOCKED
            collateral.update(failed - {mutator.expected_check})
        classes_caught += caught == len(SEEDS)
        total_caught += caught
        others = ", ".join(f"`{name}` ({count})" for name, count in sorted(collateral.items()))
        classes.append({
            "name": mutator.name, "description": mutator.description,
            "expected_check": mutator.expected_check,
            "severity": mutator.expected_severity.value,
            "caught": caught, "blocked": blocked, "scenarios": len(SEEDS),
            "collateral": dict(sorted(collateral.items())),
        })
        rows.append(
            f"| {mutator.name} | {mutator.description} | `{mutator.expected_check}` | "
            f"{mutator.expected_severity.value} | {caught}/{len(SEEDS)} | "
            f"{blocked}/{len(SEEDS)} | {others or '—'} |"
        )

    n = len(SEEDS)
    flag_only = [m.name for m in MUTATORS if m.expected_severity != CheckSeverity.CRITICAL]
    summary = {
        "report": "fault_injection",
        "source": "scripts/fault_report.py over tests/fault_injection/",
        "classes_caught": classes_caught, "classes": len(MUTATORS),
        "faults_caught": total_caught, "faults": len(MUTATORS) * n,
        "clean_scenarios": n, "clean_false_blocks": false_blocks,
        "clean_with_failed_check": clean_flags, "clean_safety_gate_blocks": gate_blocks,
        "per_class": classes,
    }
    markdown = "\n".join(
        [
            "# Fault-injection report",
            "",
            "Generated by `python scripts/fault_report.py` from `tests/fault_injection/`. "
            "CI fails if this file is out of date (`--check`).",
            "",
            "## Result",
            "",
            f"- Fault classes caught on every scenario: **{classes_caught}/{len(MUTATORS)}**",
            f"- Injected faults caught: **{total_caught}/{len(MUTATORS) * n}**",
            f"- Clean solver plans falsely blocked: **{false_blocks}/{n}** "
            f"(clean plans with any failed check: {clean_flags}/{n}; "
            f"blocked by the critical-shortage safety gate: {gate_blocks}/{n})",
            "",
            "\"Caught\" means the expected check failed. Critical checks also block the plan. "
            f"{' and '.join(f'`{name}`' for name in flag_only)} are deliberately non-blocking: "
            "a worse-than-optimal plan is shown to the operator as a high-severity finding, and "
            "instruction-like report text is flagged, never obeyed.",
            "",
            "## Per class",
            "",
            "| Class | Injected fault | Expected check | Severity | Caught | Plan blocked "
            "| Other checks that also failed |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            *rows,
            "",
            "## Corpus",
            "",
            f"{n} scenarios from `generate_scenario(seed)` for seeds {SEEDS[0]}–{SEEDS[-1]}, "
            "adjusted so every mutator applies: incident 0 is critical, every demanded unit type "
            "has an idle surplus unit, one offline unit exists per type, and each incident has a "
            "templated field report. The clean plan is the CP-SAT optimum with verbatim "
            "citations of retrieved knowledge and a SITREP rendered from the plan.",
            "",
            "## Limits of this evidence",
            "",
            "- Faults are injected one at a time by mutators written alongside the verifier. "
            "This shows each check does its job; it is not an adversarial evaluation of a live "
            "model.",
            "- Scenarios are synthetic points in urban Lucknow with straight-line (great-circle x "
            "1.4) travel times, not the OSRM road network.",
            "- SITREP numbers are checked against a fixed keyword grammar; a draft that phrases a "
            "number differently fails as unattributed rather than being understood.",
            "- Instruction detection is pattern-based and will miss paraphrased injections.",
            "",
        ]
    )
    return markdown, json.dumps(summary, indent=1, sort_keys=True) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the report is stale.")
    args = parser.parse_args()
    outputs = dict(zip((OUTPUT, OUTPUT_JSON), build(), strict=True))
    if args.check:
        for path, content in outputs.items():
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                sys.exit(f"{path.relative_to(ROOT)} is stale; run python scripts/fault_report.py")
        print("reports/fault_injection.md and .json are up to date.")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
